<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试报告</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!--    页面样式-->
    <style type="text/css">
        /*标题样式*/
        .title {
            width: auto;
            height: 60px;
            text-align: center;
            font: bolder 38px/60px "Microsoft YaHei UI";
        }

        /*汇总信息样式*/
        .summary {
            width: 90%;
            position: absolute;
            top: 120px;
            margin-left: 5%;

        }

        .text-left {
            font: bolder 20px/30px "Microsoft YaHei UI";
        }

        .left {
            width: 50%;
            float: left;

        }

        .right {
            width: 50%;
            float: right;

        }

        .desc {
            float: left;
            width: 100%;
        }

        .list-group-item span {
            font: normal 16px/38px "Microsoft YaHei UI";
            padding: 30px;

        }

        .list-group-item {
            position: relative;
            display: block;
            padding: .4rem 1.25rem;
            background-color: #fff;
            border: 1px solid rgba(0, 0, 0, .125);
        }

        /* 执行信息样式   */
        .test_info {
            width: 90%;
            position: absolute;
            top: 900px;
            margin-left: 5%;

            color: #28a745 !important;
        }

        .table td, th {
            border: solid 2px rgba(9, 122, 51, 0.11) !important;
            padding: 0;
            line-height: 40px;
            text-align: center;

        }


        select {
            border: 0;
            padding: 0;
            margin: 0;
            height: 2em;
            width: 8em;
            margin-left: 2em;
        }

        option {
            text-align: center;
            height: 36px;
            font: none 18px/36px "Microsoft YaHei UI";
            color: #28a745 !important;
        }

        .test_log {
            background: rgba(163, 171, 189, 0.15);
            width: 100%;
            height: 50px;
            border-top: none;
            border-bottom: none;
            display: none;
            text-align: left;
        }

        .test_log td {
            text-align: left;
            height: 30px;
            margin: 0;
            padding-left: 3em;
            padding-right:3em;
            font: none 18px/24px "Microsoft YaHei UI";
            color: #9e141a;
        }

        pre {
            margin: 0;
            white-space: pre-wrap;
            white-space: -moz-pre-wrap;
            white-space: -o-pre-wrap;
            word-wrap: break-word;
        }

        /*    测试图表显示*/
        .char {
            width: 90%;
            position: absolute;
            top: 450px;
            margin-left: 5%;
            color: #28a745 !important;
        }

    </style>

</head>
<body>

<!--报告标题-->
<div class="title text-success">
    <div class="shadow-lg p-3 mb-5 bg-white rounded">测试报告</div>
</div>

<!--汇总信息-->
<div class="summary">
    <p class="text-left text-success">测试结果汇总</p>
    <div class="left">
        <ul class="list-group">
            <li class="list-group-item">
                <button type="button" class="btn btn-success">测试人员</button>
                <span class="text-dark">hw</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-success">开始时间</button>
                <span class="text-dark">2020-11-20 18:48:01</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-success">执行时间</button>
                <span class="text-dark">7.75 S</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-success">用例总数</button>
                <span class="text-dark">43</span>
            </li>


        </ul>
    </div>
    <div class="right">
        <ul class="list-group">

            <li class="list-group-item">
                <button type="button" class="btn btn-success">成功用例</button>
                <span class="text-success">22</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-danger">失败用例</button>
                <span class="text-warning">21</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-warning">错误用例</button>
                <span class="text-danger">0</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-secondary">跳过用例</button>
                <span class="text-secondary">0</span>
            </li>
        </ul>
    </div>
    <div class="desc">
        <ul class="list-group">
            <li class="list-group-item">
                <button type="button" class="btn btn-success">描述信息</button>
                <span class="text-secondary">登录测试报告</span>
            </li>
        </ul>
    </div>


</div>

<!--测试图表-->
<div class="char">
    <p class="text-left text-success">图表展示</p>
    <div id="char2" style="width: 49%;height: 400px;float: left"></div>
    <div id="char" style="width: 49%;height: 400px ;float: left"></div>
</div>

<!--详细信息-->
<div class="test_info">

    <p class="text-left text-success">详细信息</p>
    <div class="table_data">

        <table class="table">
            <thead class="bg-success text-light">
            <tr>
                <th scope="col" style="width: 5%;padding: 0">编号</th>
                <th scope="col" style="width: 20%;padding: 0">
                    <span>测试类</span>
                    <select id="testClass">
                        <option>所有</option>
                        
                            <option>TestLogin</option>
                        
                            <option>TestRegister</option>
                        
                            <option>TestRecharge</option>
                        
                            <option>TestWithdraw</option>
                        
                    </select>

                </th>

                <th scope="col" style="width: 15%;padding: 0">测试方法</th>
                <th scope="col" style="width: 20%;padding: 0">用例描述</th>
                <th scope="col" style="width: 10%;padding: 0">执行时间</th>
                <th scope="col" style="width: 20%;padding: 0">

                    <span>执行结果</span>
                    <select id="testResult">
                        <option>所有</option>
                        <option class="text-success">成功</option>
                        <option class="text-danger">失败</option>
                        <option class="text-warning">错误</option>
                        <option class="text-info">跳过</option>
                    </select>

                </th>
                <th scope="col" style="width: 10%;padding: 0">详细信息</th>
            </tr>
            </thead>
            <tbody>
            
                <tr>
                    <td>1</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_1</td>
                    <td>登录成功</td>
                    <td>0.25s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 0, 'msg': 'OK'}
实际结果为{'code': 0, 'msg': 'OK'}
test_login_1 (test_01login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>2</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_2</td>
                    <td>密码错误</td>
                    <td>0.245s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 1001, 'msg': '账号信息错误'}
实际结果为{'code': 1001, 'msg': '账号信息错误'}
test_login_2 (test_01login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>3</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_3</td>
                    <td>账号错误</td>
                    <td>0.236s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 1002, 'msg': '账号信息错误'}
实际结果为{'code': 1001, 'msg': '账号信息错误'}
test_login_3 (test_01login.TestLogin)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_01login.py", line 40, in test_login
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_01login.py", line 36, in test_login
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 1001, 'msg': '账号信息错误'} != {'code': 1002, 'msg': '账号信息错误'}
- {'code': 1001, 'msg': '账号信息错误'}
?             ^

+ {'code': 1002, 'msg': '账号信息错误'}
?             ^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>4</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_4</td>
                    <td>账号为空</td>
                    <td>0.116s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 1, 'msg': '手机号码为空'}
实际结果为{'code': 1, 'msg': '手机号码为空'}
test_login_4 (test_01login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>5</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_5</td>
                    <td>密码为空</td>
                    <td>0.114s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 1, 'msg': '密码为空'}
实际结果为{'code': 1, 'msg': '密码为空'}
test_login_5 (test_01login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>6</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_01</td>
                    <td>正常注册(类型、注册名为空)</td>
                    <td>0.473s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 0, 'msg': 'OK'}
test_register_01 (test_02register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>7</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_02</td>
                    <td>正常注册(类型为0、注册名为空)</td>
                    <td>0.443s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 0, 'msg': 'OK'}
test_register_02 (test_02register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>8</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_03</td>
                    <td>正常注册(类型为空、注册名正常)</td>
                    <td>0.109s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 2, 'msg': '无效的手机格式'}
test_register_03 (test_02register.TestRegister)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_02register.py", line 48, in test_register
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_02register.py", line 43, in test_register
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '无效的手机格式'} != {'code': 0, 'msg': 'OK'}
- {'code': 2, 'msg': '无效的手机格式'}
?          ^          ^^^^^^^

+ {'code': 0, 'msg': 'OK'}
?          ^          ^^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>9</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_04</td>
                    <td>注册失败(类型格式异常、注册名为空)</td>
                    <td>0.325s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 1004, 'msg': 'JSON parse error: Cannot deserialize value of type `java.lang.Integer` from String "流水无痕": not a valid Integer value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Integer` from String "流水无痕": not a valid Integer value\n at [Source: (PushbackInputStream); line: 1, column: 60] (through reference chain: com.lemon.pojo.Member["type"])'}
test_register_04 (test_02register.TestRegister)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_02register.py", line 48, in test_register
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_02register.py", line 43, in test_register
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 1004, 'msg': 'JSON parse error: Cannot de[380 chars]"])'} != {'code': 2, 'msg': '格式错误'}
+ {'code': 2, 'msg': '格式错误'}
- {'code': 1004,
-  'msg': 'JSON parse error: Cannot deserialize value of type '
-         '`java.lang.Integer` from String "流水无痕": not a valid Integer value; '
-         'nested exception is '
-         'com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot '
-         'deserialize value of type `java.lang.Integer` from String "流水无痕": not '
-         'a valid Integer value\n'
-         ' at [Source: (PushbackInputStream); line: 1, column: 60] (through '
-         'reference chain: com.lemon.pojo.Member["type"])'}
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>10</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_05</td>
                    <td>注册失败(类型为空、注册名大于10位)</td>
                    <td>0.321s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 2, 'msg': '用户昵称长度超过10位'}
test_register_05 (test_02register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>11</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_06</td>
                    <td>注册失败(手机号已被注册)</td>
                    <td>0.103s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 2, 'msg': '无效的手机格式'}
test_register_06 (test_02register.TestRegister)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_02register.py", line 48, in test_register
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_02register.py", line 43, in test_register
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '无效的手机格式'} != {'code': 2, 'msg': '账号已存在'}
- {'code': 2, 'msg': '无效的手机格式'}
?                     ^^^^^^^

+ {'code': 2, 'msg': '账号已存在'}
?                     ^^^^^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>12</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_07</td>
                    <td>注册失败(手机号过长)</td>
                    <td>0.108s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 2, 'msg': '无效的手机格式'}
test_register_07 (test_02register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>13</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_08</td>
                    <td>注册失败(手机号过短)</td>
                    <td>0.111s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 2, 'msg': '无效的手机格式'}
test_register_08 (test_02register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>14</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_09</td>
                    <td>注册失败(手机号包含特殊字符)</td>
                    <td>0.106s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 2, 'msg': '无效的手机格式'}
test_register_09 (test_02register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>15</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_10</td>
                    <td>注册失败(手机号为空)</td>
                    <td>0.113s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 1, 'msg': '手机号为空'}
test_register_10 (test_02register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>16</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_11</td>
                    <td>注册失败(密码为空)</td>
                    <td>0.106s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 1, 'msg': '密码为空'}
test_register_11 (test_02register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>17</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_12</td>
                    <td>注册失败(类型超出范围)</td>
                    <td>0.105s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 2, 'msg': '不支持的用户类型'}
test_register_12 (test_02register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>18</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_13</td>
                    <td>注册失败(密码过长)</td>
                    <td>0.111s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 2, 'msg': '密码格式为8到16位'}
test_register_13 (test_02register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>19</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_14</td>
                    <td>注册失败(密码过短)</td>
                    <td>0.111s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre><class 'dict'>
{'code': 2, 'msg': '密码格式为8到16位'}
test_register_14 (test_02register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>20</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_01</td>
                    <td>充值成功</td>
                    <td>0.281s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>[{'leave_amount': Decimal('5112128.26')}] <class 'list'> {'leave_amount': Decimal('5112128.26')}
预期结果为{'code': 0, 'msg': 'OK'}
实际结果为{'code': 0, 'msg': 'OK'}
test_recharge_01 (test_03recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>21</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_02</td>
                    <td>充值0.01成功</td>
                    <td>0.283s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>[{'leave_amount': Decimal('5122129.14')}] <class 'list'> {'leave_amount': Decimal('5122129.14')}
预期结果为{'code': 0, 'msg': 'OK'}
实际结果为{'code': 0, 'msg': 'OK'}
test_recharge_02 (test_03recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>22</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_03</td>
                    <td>充值500000成功</td>
                    <td>0.287s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>[{'leave_amount': Decimal('5122129.15')}] <class 'list'> {'leave_amount': Decimal('5122129.15')}
预期结果为{'code': 0, 'msg': 'OK'}
实际结果为{'code': 0, 'msg': 'OK'}
test_recharge_03 (test_03recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>23</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_04</td>
                    <td>充值0失败</td>
                    <td>0.115s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
实际结果为{'code': 0, 'msg': 'OK'}
test_recharge_04 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 0, 'msg': 'OK'} != {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
- {'code': 0, 'msg': 'OK'}
+ {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>24</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_05</td>
                    <td>用户id为空</td>
                    <td>0.109s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 1, 'msg': '用户id不能为空'}
实际结果为{'code': 1, 'msg': '用户id为空'}
test_recharge_05 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 1, 'msg': '用户id为空'} != {'code': 1, 'msg': '用户id不能为空'}
- {'code': 1, 'msg': '用户id为空'}
+ {'code': 1, 'msg': '用户id不能为空'}
?                         ++

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>25</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_06</td>
                    <td>充值金额为空</td>
                    <td>0.111s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '金额必须是数值型'}
实际结果为{'code': 2, 'msg': '余额必须为数值型'}
test_recharge_06 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '余额必须为数值型'} != {'code': 2, 'msg': '金额必须是数值型'}
- {'code': 2, 'msg': '余额必须为数值型'}
?                     ^   ^

+ {'code': 2, 'msg': '金额必须是数值型'}
?                     ^   ^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>26</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_07</td>
                    <td>用户id不存在</td>
                    <td>0.103s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 1007, 'msg': '无权限访问，请检查参数'}
实际结果为{'code': 1007, 'msg': '无权限访问，请检查参数'}
test_recharge_07 (test_03recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>27</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_08</td>
                    <td>充值金额为负值</td>
                    <td>0.108s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
实际结果为{'code': 2, 'msg': '余额必须大于0并且小于或者等于500000'}
test_recharge_08 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '余额必须大于0并且小于或者等于500000'} != {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
- {'code': 2, 'msg': '余额必须大于0并且小于或者等于500000'}
?                     ^

+ {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
?                     ^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>28</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_09</td>
                    <td>充值金额超出范围</td>
                    <td>0.109s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
实际结果为{'code': 2, 'msg': '余额必须大于0并且小于或者等于500000'}
test_recharge_09 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '余额必须大于0并且小于或者等于500000'} != {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
- {'code': 2, 'msg': '余额必须大于0并且小于或者等于500000'}
?                     ^

+ {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
?                     ^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>29</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_10</td>
                    <td>充值金额3位小数</td>
                    <td>0.108s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '手机号为空'}
实际结果为{'code': 2, 'msg': '余额小数超过两位'}
test_recharge_10 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '余额小数超过两位'} != {'code': 2, 'msg': '手机号为空'}
- {'code': 2, 'msg': '余额小数超过两位'}
?                     ^^^^^^^^

+ {'code': 2, 'msg': '手机号为空'}
?                     ^^^^^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>30</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_11</td>
                    <td>充值金额为字符串格式</td>
                    <td>0.122s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '格式错误'}
实际结果为{'code': 0, 'msg': 'OK'}
test_recharge_11 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 0, 'msg': 'OK'} != {'code': 2, 'msg': '格式错误'}
- {'code': 0, 'msg': 'OK'}
?          ^          ^^

+ {'code': 2, 'msg': '格式错误'}
?          ^          ^^^^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>31</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_12</td>
                    <td>用户名字字符串格式</td>
                    <td>0.118s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '格式错误'}
实际结果为{'code': 0, 'msg': 'OK'}
test_recharge_12 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_03recharge.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 0, 'msg': 'OK'} != {'code': 2, 'msg': '格式错误'}
- {'code': 0, 'msg': 'OK'}
?          ^          ^^

+ {'code': 2, 'msg': '格式错误'}
?          ^          ^^^^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>32</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_recharge_01</td>
                    <td>提现成功</td>
                    <td>0.283s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>[{'leave_amount': Decimal('5623230.91')}] <class 'list'> {'leave_amount': Decimal('5623230.91')}
预期结果为{'code': 0, 'msg': 'OK'}
实际结果为{'code': 0, 'msg': 'OK'}
test_recharge_01 (test_04withdraw.TestWithdraw)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>33</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_recharge_02</td>
                    <td>提现0.01成功</td>
                    <td>0.302s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>[{'leave_amount': Decimal('5613230.03')}] <class 'list'> {'leave_amount': Decimal('5613230.03')}
预期结果为{'code': 0, 'msg': 'OK'}
实际结果为{'code': 0, 'msg': 'OK'}
test_recharge_02 (test_04withdraw.TestWithdraw)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>34</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_recharge_03</td>
                    <td>提现500000成功</td>
                    <td>0.286s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>[{'leave_amount': Decimal('5613230.02')}] <class 'list'> {'leave_amount': Decimal('5613230.02')}
预期结果为{'code': 0, 'msg': 'OK'}
实际结果为{'code': 0, 'msg': 'OK'}
test_recharge_03 (test_04withdraw.TestWithdraw)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>35</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_recharge_04</td>
                    <td>提现0失败</td>
                    <td>0.114s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
实际结果为{'code': 0, 'msg': 'OK'}
test_recharge_04 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 0, 'msg': 'OK'} != {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
- {'code': 0, 'msg': 'OK'}
+ {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>36</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_recharge_05</td>
                    <td>用户id为空</td>
                    <td>0.105s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 1, 'msg': '用户id不能为空'}
实际结果为{'code': 1, 'msg': '会员id为空'}
test_recharge_05 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 1, 'msg': '会员id为空'} != {'code': 1, 'msg': '用户id不能为空'}
- {'code': 1, 'msg': '会员id为空'}
?                     ^^

+ {'code': 1, 'msg': '用户id不能为空'}
?                     ^^  ++

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>37</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_recharge_06</td>
                    <td>提现金额为空</td>
                    <td>0.103s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '金额必须是数值型'}
实际结果为{'code': 1, 'msg': '余额为空'}
test_recharge_06 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 1, 'msg': '余额为空'} != {'code': 2, 'msg': '金额必须是数值型'}
- {'code': 1, 'msg': '余额为空'}
?          ^          ^ ^^

+ {'code': 2, 'msg': '金额必须是数值型'}
?          ^          ^ ^^^^^^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>38</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_recharge_07</td>
                    <td>用户id不存在</td>
                    <td>0.111s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 1007, 'msg': '无权限访问，请检查参数'}
实际结果为{'code': 2, 'msg': '会员不存在'}
test_recharge_07 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '会员不存在'} != {'code': 1007, 'msg': '无权限访问，请检查参数'}
- {'code': 2, 'msg': '会员不存在'}
+ {'code': 1007, 'msg': '无权限访问，请检查参数'}
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>39</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_recharge_08</td>
                    <td>提现金额为负值</td>
                    <td>0.11s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
实际结果为{'code': 2, 'msg': '余额必须大于0并且小于或者等于5000000'}
test_recharge_08 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '余额必须大于0并且小于或者等于5000000'} != {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
- {'code': 2, 'msg': '余额必须大于0并且小于或者等于5000000'}
?                     ^                    -

+ {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
?                     ^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>40</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_recharge_09</td>
                    <td>提现金额超出范围</td>
                    <td>0.106s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
实际结果为{'code': 2, 'msg': '余额必须大于0并且小于或者等于5000000'}
test_recharge_09 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '余额必须大于0并且小于或者等于5000000'} != {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
- {'code': 2, 'msg': '余额必须大于0并且小于或者等于5000000'}
?                     ^                    -

+ {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
?                     ^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>41</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_recharge_10</td>
                    <td>提现金额3位小数</td>
                    <td>0.109s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '手机号为空'}
实际结果为{'code': 2, 'msg': '余额小数超过两位'}
test_recharge_10 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '余额小数超过两位'} != {'code': 2, 'msg': '手机号为空'}
- {'code': 2, 'msg': '余额小数超过两位'}
?                     ^^^^^^^^

+ {'code': 2, 'msg': '手机号为空'}
?                     ^^^^^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>42</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_recharge_11</td>
                    <td>提现金额为字符串格式</td>
                    <td>0.117s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '格式错误'}
实际结果为{'code': 0, 'msg': 'OK'}
test_recharge_11 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 0, 'msg': 'OK'} != {'code': 2, 'msg': '格式错误'}
- {'code': 0, 'msg': 'OK'}
?          ^          ^^

+ {'code': 2, 'msg': '格式错误'}
?          ^          ^^^^

</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>43</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_recharge_12</td>
                    <td>用户名字字符串格式</td>
                    <td>0.119s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果为{'code': 2, 'msg': '格式错误'}
实际结果为{'code': 0, 'msg': 'OK'}
test_recharge_12 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\common\myddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 70, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\lemon\day12_project\testcase\test_04withdraw.py", line 63, in test_recharge
    self.assertEqual(res2,expected)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
</pre>
                        

                            <pre>  File "D:\Program Files\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: {'code': 0, 'msg': 'OK'} != {'code': 2, 'msg': '格式错误'}
- {'code': 0, 'msg': 'OK'}
?          ^          ^^

+ {'code': 2, 'msg': '格式错误'}
?          ^          ^^^^

</pre>
                        
                        
                    </td>
                </tr>
            

            </tbody>
        </table>
    </div>

    <div style="height: 200px"></div>
</div>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js"></script>

<script>
    var tbodyTr = $('tbody tr');
    var testResult = $("#testResult");
    var testClass = $("#testClass");
    <!--    用例执行详细信息显示切换-->
    $(".btn_info").click(function () {
        $(this).parent().parent().next().toggle();

    });
    // 当选择用例类之后触发
    testClass.change(function () {
        var cls = $(this).val();
        var res = testResult.val();
        elementDisplay(cls, res);
        sort()
    });
    testResult.change(function () {
        var res = $(this).val();
        var cls = testClass.val();
        elementDisplay(cls, res);
        sort()
    });

    function elementDisplay(cls, res) {
        // 用例数据的显示
        if (cls === "所有") {
            if (res === "所有") {
                tbodyTr.has('button').show();
            } else if (res === '成功') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.text-success').show()

            } else if (res === '失败') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.text-danger').show()

            } else if (res === '错误') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.text-warning').show()

            } else if (res === '跳过') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.text-info').show()
            }
        } else {
            if (res === "所有") {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').show()
            } else if (res === '成功') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').has('.text-success').show()
            } else if (res === '失败') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').has('.text-danger').show()
            } else if (res === '错误') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').has('.text-warning').show()
            } else if (res === '跳过') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').has('.text-info').show()
            }
        }
    }

    function sort() {
        //重新排列显示序号
        // 选择所有可以见的tr
        var visibleTr = tbodyTr.filter(":visible");

        visibleTr.each(function (index, element) {
            element.firstElementChild.innerHTML = index + 1;

        })

    }


</script>

<script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('char'));
    var myChart2 = echarts.init(document.getElementById('char2'));
    // 指定图表的配置项和数据
    option = {
        color: ['#00a10a', '#ddb518', 'rgba(204,46,41,0.73)', '#85898c'],
        tooltip: {
            trigger: 'item',
            formatter: '{a} <br/>{b}: {c} ({d}%)'
        },
        legend: {
            orient: 'vertical',
            left: 10,
            data: ['通过', '失败', '错误', '跳过']
        },
        series: [
            {
                name: '测试结果',
                type: 'pie',
                radius: ['50%', '70%'],
                avoidLabelOverlap: false,
                label: {
                    show: false,
                    position: 'center'
                },
                emphasis: {
                    label: {
                        show: true,
                        fontSize: '30',
                        fontWeight: 'bold'
                    }
                },
                labelLine: {
                    show: false
                },
                data: [
                    {value: 22, name: '通过'},
                    {value: 21, name: '失败'},
                    {value: 0, name: '错误'},
                    {value: 0, name: '跳过'}
                ]
            }
        ]
    };
    option2 = {
        tooltip: {
            formatter: '{a} <br/>{b} : {c}%'
        },
        toolbox: {
            feature: {
                restore: {},
                saveAsImage: {}
            }
        },
        series: [
            {
                name: '测试结果',
                type: 'gauge',
                detail: {formatter: '51.16%'},
                data: [{value: '51.16', name: '用例通过率'}],
                axisLine: {
                    lineStyle: {
                        color: [
                            [0.2, '#c20000'],
                            [0.8, '#ddb518'],
                            [1, '#00a10a']]
                    }
                }
            }
        ]
    };


    myChart2.setOption(option2);
    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
</script>


</body>
</html>